### PR TITLE
finally faq jerk is fixed now, new code for js written.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
live link: 
http://anupamdagar.me/hack-in-the-north-preview-repo/main

### CODE REVIEW

**Comment by gauthamzz** [comment]
can we make sure that only one faq is open at a time

**Comment by Anupam-dagar** [comment]
i think if condition will do it, giving it a try.

**Comment by Anupam-dagar** [comment]
it's done :smile:

**Comment by gauthamzz** [comment]
LGTM :+1:

**Pull request merged**
