### PR TITLE
responsive

### PR DESCRIPTION
**Pull request by OrionStar25**
https://orionstar25.github.io/hackinthenorth.github.io/main/

about section 320px and below is overflowing. everything else is responsive.
I'd appreciate if someone does that. Thanks.

### CODE REVIEW

**Comment by gauthamzz** [comment]
merge conflicts solve

**Comment by OrionStar25** [comment]
I'll loose my commits then

**Comment by gauthamzz** [comment]
how will you loose commits fixing merge conflicts , anyway this is not resposive 
deepinscreenshot_select-area_20171207012802

also heroku comes before topcoder in mobile 
deepinscreenshot_select-area_20171207012912

various veiws and send pr ,this is not reponsie at all :/ 
deepinscreenshot_select-area_20171207012950

**Comment by OrionStar25** [comment]
About section i cant. thats things doesnt make sense to me.

**Comment by gauthamzz** [comment]
Its okay take your time. @Anupam-dagar help her

**Pull request closed without merging**
