### PR TITLE
fixed centering of about section

### PR DESCRIPTION
**Pull request by Anupam-dagar**

### CODE REVIEW

**Comment by gauthamzz** [comment]
LGTM :+1:

**Comment by gauthamzz** [comment]
LGTM :+1:

**Comment by gauthamzz** [comment]
Sorry @Anupam-dagar its still not fixed

**Comment by Anupam-dagar** [comment]
I had to do a cache clear to see the changes.
it looks like this
screenshot from 2017-11-08 23-57-39

**Comment by gauthamzz** [comment]
screen resolution diffrent :smile: Its still the same for me. Go to inspect and change the screen size and see

**Comment by Anupam-dagar** [comment]
ohhh, fixing :stuck_out_tongue:

**Pull request merged**
