### PR TITLE
Update about section content

### PR DESCRIPTION
**Pull request by mubaris**
I've updated the about section contents. Not so sure about the class names.

### CODE REVIEW

**Comment by pradyumna1** [comment]
Thanks @mubaris

**Comment by hackerkid** [comment]
@pradyumna1 Can you revert the changes. The home page look crowded.

**Comment by pradyumna1** [comment]
@hackerkid done.. @mubaris  I will use your content later.

**Comment by hackerkid** [comment]
@SaptakS

**Comment by mubaris** [comment]
@pradyumna1 No worries

**Pull request merged**
