### PR TITLE
update sponsors section

### PR DESCRIPTION
**Pull request by yasharmaster**

### CODE REVIEW

**Comment by hackerkid** [comment]
@yasharmaster Can you check the status of Geeksforgeeks with Abhinav Khare. I am not sure they confirmed it.

**Comment by hackerkid** [comment]
Gold section looks messed up. And codepen too. We should probably use a different color instead of pink.

**Comment by yasharmaster** [comment]
@hackerkid geeksforgeeks has been confirmed, abhinav has commented on the sponsorship thread regarding this

**Comment by hackerkid** [comment]
@yasharmaster They cancelled. Check facebook.

**Pull request merged**
