### PR TITLE
Added Prizes for top 7 teams in the 'prizes and rewards' section

### PR DESCRIPTION
**Pull request by arpitmisraw**

### CODE REVIEW

**Comment by gauthamzz** [comment]
live link ?

**Comment by gauthamzz** [comment]
live link ?
are images compressed ?

**Comment by arpitmisraw** [comment]
https://arpitmisraw.github.io/hackinthenorth.github.io/

Yes, they are.

**Comment by gauthamzz** [comment]
I think it should be continous, looks weird. the gap in between

**Comment by arpitmisraw** [comment]
@gauthamzz Which part?

**Comment by arpitmisraw** [comment]
@CosmicCoder96  I'll change it.

**Comment by arpitmisraw** [comment]
@CosmicCoder96 The aspect ratios have been restored. Please have a look.

**Pull request merged**
