### PR TITLE
Update main.css

### PR DESCRIPTION
**Pull request by arpt-svt**
Added transitions to buttons .btn1 .btn2 .btn3

### CODE REVIEW

**Comment by hackerkid** [comment]
@arpt-svt Can you post some screenshots!!

**Comment by arpt-svt** [comment]
Screenshot of what?
You want to see transition in screenshot?

**Comment by gauthamzz** [comment]
Can you enable gh pages and provide lllink

**Comment by arpt-svt** [comment]
<a href="https://larave-test.000webhostapp.com/">Here </a>is the link of hosted pages

**Comment by hackerkid** [comment]
@arpt-svt You can always make a GIF!!!

**Comment by arpt-svt** [comment]
here is the link https://arpt-svt.github.io/hackinthenorth1.github.io/

**Comment by gauthamzz** [comment]
Thank you, But we are working on the new website . If you would like to help . Reach us out in facebook or gitter

**Pull request closed without merging**
