### PR TITLE
add preloader

### PR DESCRIPTION
**Pull request by OrionStar25**
https://orionstar25.github.io/hackinthenorth.github.io/

### CODE REVIEW

**Comment by gauthamzz** [comment]
No preloader , we have lazy loading on logo. The speed is almost same. Why show this chains. And if you are making preloader make like the logo atleast.

**Comment by gauthamzz** [comment]
Your preloader loads slower than the present website 😅

**Comment by CosmicCoder96** [comment]
@gauthamzz we do need a preloader, let's work on this to make it suitable. THe website loads like crap on mobile with half the images not done till like 20 seconds in some cases, lazy loading if there, has  not been implemented correctly. I posted a screenshot in the HINT website chat, so as to why we need a preloader :p

**Comment by CosmicCoder96** [comment]
@OrionStar25 The idea is to implement a non gif preloader, use the image of the cogs in the hint logo and make it spin using css, that way the quality is not compromised.

**Comment by vivekanand1101** [comment]
Nice commit messages. Also, check this one out: https://mathiasbynens.github.io/rel-noopener/

**Comment by gauthamzz** [comment]
If it looks like hint logo then it’s okay , this preloader was bad

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 lazy loading is working fine, i checked it :stuck_out_tongue: 
it's just that landing page is the first to load so lazy load will not be effective for it :stuck_out_tongue:

**Comment by gauthamzz** [comment]
can you compress the images on the website as well,it feels like preloader is going forever.

**Comment by gauthamzz** [comment]
the prizes section and new sponsors are not compressed and doenst have lazy loading applied.

**Comment by OrionStar25** [comment]
@gauthamzz ignore this commit please, i was just trying out something. I thought this pr was closed .

**Pull request closed without merging**
