### PR TITLE
fixed about section responsive issue and added schedule

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Please take a look at the schedule, by default color almost matches with the site, if it is not fine then I will change.Responsive check is done for the schedule.
live link:
http://anupamdagar.me/hack-in-the-north-preview-repo/main/

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
i can make it wider but then height of the section will reduce.
There is a shadow dropdown currently on the card, I will make it a little more on hover.

**Comment by yasharmaster** [comment]
Yeah, the gradient looks good as a background but not so much on the buttons.

**Comment by Anupam-dagar** [comment]
these buttons look cool
https://codepen.io/deineko/pen/jrmmoQ
should i replace current one with these?

**Comment by yasharmaster** [comment]
Yep these look way better!

On 05-Nov-2017 11:51 AM, "Anupam Dagar" <notifications@github.com> wrote:

these buttons look cool
https://codepen.io/deineko/pen/jrmmoQ
should i replace current one with these?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/HackInTheNorth/hackinthenorth.github.io/pull/132#issuecomment-341951963>,
or mute the thread

**Pull request merged**
