### PR TITLE
changed gradient to hint's logo color

### PR DESCRIPTION
**Pull request by Anupam-dagar**
live link: http://anupamdagar.me/hack-in-the-north-preview-repo/main/

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
@gauthamzz @yasharmaster

**Comment by yasharmaster** [comment]
IMO the previous gradient looks better than our logo's gradient :stuck_out_tongue:
@gauthamzz what do you think?

**Comment by gauthamzz** [comment]
yeah these look weird .The about secitiiion is very very bad

**Comment by Anupam-dagar** [comment]
About section in terms of gradient,  right?
Should I revert back  to previous gradient

**Comment by gauthamzz** [comment]
about in terms of the weird arrow like thing :smile:

**Comment by Anupam-dagar** [comment]
oh, that is just for representation purposes only :stuck_out_tongue: , we will ask nabeel to make something good and place it there.

**Comment by gauthamzz** [comment]
minimal is fine.

**Comment by Anupam-dagar** [comment]
okay i will keep a card only

**Pull request closed without merging**
