### PR TITLE
added animation in about and faq section [WIP]

### PR DESCRIPTION
**Pull request by Anupam-dagar**
live link: http://anupamdagar.me/hack-in-the-north-preview-repo/main/

### CODE REVIEW

**Comment by gauthamzz** [comment]
Could you change  that applications are open 

In the mobile view the nav bar looks too huge relative to screen size

**Comment by gauthamzz** [comment]
See in mobile view the FAQ looks too clustered.

**Comment by Anupam-dagar** [comment]
Currently we were setting up the basic structure of the website,  I'll check and fix it up.

**Comment by gauthamzz** [comment]
Yeah sounds good.

**Comment by Anupam-dagar** [comment]
@yasharmaster yeah sure, I will create one PR for one feature fix. :smile:

**Pull request merged**
