### PR TITLE
add sponsors and fix alignments

### PR DESCRIPTION
**Pull request by OrionStar25**
https://orionstar25.github.io/hackinthenorth.github.io/

### CODE REVIEW

**Comment by gauthamzz** [comment]
are the images compressed, the site is taking too long. Could you also compress the photos in the website if they are not yet compressed (diversity section)

**Comment by OrionStar25** [comment]
I have to add one more sponsor and change certain orders. compressing @Anupam-dagar would do :)

**Comment by OrionStar25** [comment]
@gauthamzz check now please

**Comment by gauthamzz** [comment]
You do , there are online websites. He is busy in opencode and you are done by website from now

**Comment by OrionStar25** [comment]
There you go, it shows a green good  :3

**Comment by gauthamzz** [comment]
yes im happy

**Pull request merged**
